name: nextflow_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - alsa-lib=1.2.8
  - arrow-cpp=14.0.2
  - aws-c-auth=0.6.21
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.17
  - aws-c-http=0.7.0
  - aws-c-io=0.13.12
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.2.1
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - backports=1.0
  - backports.zoneinfo=0.2.1
  - blas=2.17
  - boost-cpp=1.78.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cairo=1.16.0
  - coreutils=8.25
  - curl=8.5.0
  - expat=2.6.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - graphite2=1.3.13
  - grpc-cpp=1.48.2
  - gtfparse=2.5.0
  - harfbuzz=6.0.0
  - icu=70.1
  - k8=0.2.5
  - keyutils=1.6.1
  - krb5=1.21.2
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20211102.0
  - libblas=3.8.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.8.0
  - libcups=2.3.3
  - libcurl=8.5.0
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.1
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-ng=13.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.78.4
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjemalloc=5.3.0
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.10
  - libpng=1.6.43
  - libprotobuf=3.20.3
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.15.0
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - minimap2=2.26
  - ncurses=6.4
  - nextflow=23.10.1
  - numpy=1.20.3
  - numpy-base=1.18.5
  - openjdk=17.0.3
  - openssl=3.2.1
  - orc=1.7.4
  - pandas=2.0.0
  - parallel=20240122
  - pcre2=10.42
  - perl=5.32.1
  - pip=24.0
  - pixman=0.43.2
  - polars=0.20.13
  - pthread-stubs=0.4
  - pyarrow=14.0.2
  - pysam=0.22.0
  - python=3.8.18
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.8
  - pytz=2024.1
  - re2=2022.04.01
  - readline=8.2
  - s2n=1.3.31
  - salmon=1.10.2
  - samtools=1.19.2
  - subread=2.0.1
  - setuptools=69.1.1
  - six=1.16.0
  - snappy=1.1.10
  - tbb=2021.9.0
  - tk=8.6.13
  - typing_extensions=4.10.0
  - tzdata=2024a
  - utf8proc=2.6.1
  - wheel=0.42.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.5
